### register
POST {{url}}/api/user/user/register
Content-Type: application/json
lang: en

{
  "account": "tta123123",
  "password": "a1231231",
  "country": "tw",
  "city": "gaoxiong",
  "phone": "123123",
  "email": "email",
  "realName": "tom2"
}

### Login
POST {{url}}/api/user/user/login
Content-Type: application/json
lang: zh

{
  "account": "join",
  "password": "a1231231"
}

> {%
    client.global.set("token", "Bearer " + response.body.data.token);
%}

### Get Login Info
GET {{url}}/api/user/user/info
Authorization: {{token}}

### Update Login pass
PUT {{url}}/api/user/user/pass
Authorization: {{token}}
Content-Type: application/json

{
  "oldPass": "a1231232",
  "newPass": "a1231231"
}

### set pay pass
PUT {{url}}/api/user/user/setPayPass
Authorization: {{token}}
Content-Type: application/json

{
  "pass": "123456"
}