### banks
GET {{url}}/api/user/wallet/banks
Authorization: {{token}}

### logs
GET {{url}}/api/user/wallet/logs?page=1&size=10&balanceCode=400
Authorization: {{token}}

### balanceCodes
GET {{url}}/api/user/wallet/balanceCodes
Authorization: {{token}}
lang: en

### get platform deposit
GET {{url}}/api/user/wallet/deposit/platform
Authorization: {{token}}

### create deposit
POST {{url}}/api/user/wallet/deposit/create
Authorization: {{token}}
Content-Type: application/json

{
  "payId": 85,
  "amount": 100,
  "transferOrderNo": "dfasfewfawf",
  "transerImg": "Uvteyd.png"
}

### bind withdraw account item
POST {{url}}/api/user/wallet/withdraw/account/bind
Authorization: {{token}}
Content-Type: application/json

{
  "bankId": 48,
  "address": "3333331233333",
  "title": "John"
}

### list withdraw account item
GET {{url}}/api/user/wallet/withdraw/account/list?page=1&size=10
Authorization: {{token}}


### set default withdraw account
PUT {{url}}/api/user/wallet/withdraw/account/setDefault?id=1694635985192620032
Authorization: {{token}}

### del withdraw account
DELETE {{url}}/api/user/wallet/withdraw/account/del
Authorization: {{token}}
Content-Type: application/json

{
  "payPass": "123456",
  "id": 1694644781126258688
}

### create withdrw
POST {{url}}/api/user/wallet/withdraw/create
Authorization: {{token}}
Content-Type: application/json

{
  "amountItemId": 85,
  "amount": 100,
  "withdrawAccountId": 1694635985192620032
}
### change pay pass
PUT {{url}}/api/user/wallet/withdraw/payPass
Authorization: {{token}}
Content-Type: application/json

{
  "pass": "a1231231",
  "payPass": "123456",
  "title": "John",
  "address": "3123441333"
}