### register
POST {{url}}/api/user/register
Content-Type: application/json
lang: en

{
  "account": "tta123123",
  "password": "a",
  "country": "tw",
  "city": "gaoxiong",
  "phone": "123123",
  "email": "email",
  "realName": "tom2"
}

### Login
POST {{url}}/api/user/login
Content-Type: application/json
lang: zh

{
  "uname": "join",
  "pass": "a1231231"
}

> {%
    client.global.set("token", "Bearer " + response.body.data.token);
%}

### Get Login Info
GET {{url}}/api/user/info
Authorization: {{token}}

