### get captcha
GET {{url}}/api/user/getCaptcha?captchaId=1

### register
POST {{url}}/api/user/register
Content-Type: application/json

{
  "account": "join6",
  "password": "a123456",
  "country": "tw",
  "city": "gaoxiong"
}

### Login
POST {{url}}/api/user/login
Content-Type: application/json

{
  "uname": "admin",
  "pass": "1"
}

> {%
    client.global.set("token", "Bearer " + response.body.data.token);
%}

### Get Login Info
GET {{url}}/api/sys/admin/user_info
Authorization: {{token}}

