### banks
GET {{url}}/api/wallet/banks
Authorization: {{token}}

### logs
GET {{url}}/api/wallet/logs?page=1&size=10&balanceCode=400
Authorization: {{token}}

### balanceCodes
GET {{url}}/api/wallet/balanceCodes
Authorization: {{token}}
lang: en

### get platform deposit
GET {{url}}/api/wallet/deposit/platform
Authorization: {{token}}

### create deposit
POST {{url}}/api/wallet/deposit/create
Authorization: {{token}}
Content-Type: application/json

{
  "payId": 85,
  "amount": 100,
  "transferOrderNo": "dfasfewfawf",
  "transerImg": "adfafae"
}

