// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalAmountItemDao is internal type for wrapping internal DAO implements.
type internalAmountItemDao = *internal.AmountItemDao

// amountItemDao is the data access object for table u_amount_item.
// You can define custom methods on it to extend its functionality as you wish.
type amountItemDao struct {
	internalAmountItemDao
}

var (
	// AmountItem is globally public accessible object for table u_amount_item operations.
	AmountItem = amountItemDao{
		internal.NewAmountItemDao(),
	}
)

// Fill with you ideas below.
