// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalAmountCategoryDao is internal type for wrapping internal DAO implements.
type internalAmountCategoryDao = *internal.AmountCategoryDao

// amountCategoryDao is the data access object for table u_amount_category.
// You can define custom methods on it to extend its functionality as you wish.
type amountCategoryDao struct {
	internalAmountCategoryDao
}

var (
	// AmountCategory is globally public accessible object for table u_amount_category operations.
	AmountCategory = amountCategoryDao{
		internal.NewAmountCategoryDao(),
	}
)

// Fill with you ideas below.
