// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalDepositDao is internal type for wrapping internal DAO implements.
type internalDepositDao = *internal.DepositDao

// depositDao is the data access object for table o_deposit.
// You can define custom methods on it to extend its functionality as you wish.
type depositDao struct {
	internalDepositDao
}

var (
	// Deposit is globally public accessible object for table o_deposit operations.
	Deposit = depositDao{
		internal.NewDepositDao(),
	}
)

// Fill with you ideas below.
