// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalDigitalAccountDao is internal type for wrapping internal DAO implements.
type internalDigitalAccountDao = *internal.DigitalAccountDao

// digitalAccountDao is the data access object for table u_digital_account.
// You can define custom methods on it to extend its functionality as you wish.
type digitalAccountDao struct {
	internalDigitalAccountDao
}

var (
	// DigitalAccount is globally public accessible object for table u_digital_account operations.
	DigitalAccount = digitalAccountDao{
		internal.NewDigitalAccountDao(),
	}
)

// Fill with you ideas below.
