// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalLeagueDao is internal type for wrapping internal DAO implements.
type internalLeagueDao = *internal.LeagueDao

// leagueDao is the data access object for table p_league.
// You can define custom methods on it to extend its functionality as you wish.
type leagueDao struct {
	internalLeagueDao
}

var (
	// League is globally public accessible object for table p_league operations.
	League = leagueDao{
		internal.NewLeagueDao(),
	}
)

// Fill with you ideas below.
