// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalMenuApiRuleDao is internal type for wrapping internal DAO implements.
type internalMenuApiRuleDao = *internal.MenuApiRuleDao

// menuApiRuleDao is the data access object for table s_menu_api_rule.
// You can define custom methods on it to extend its functionality as you wish.
type menuApiRuleDao struct {
	internalMenuApiRuleDao
}

var (
	// MenuApiRule is globally public accessible object for table s_menu_api_rule operations.
	MenuApiRule = menuApiRuleDao{
		internal.NewMenuApiRuleDao(),
	}
)

// Fill with you ideas below.
