// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalSoccerOrderSettleDao is internal type for wrapping internal DAO implements.
type internalSoccerOrderSettleDao = *internal.SoccerOrderSettleDao

// soccerOrderSettleDao is the data access object for table o_soccer_order_settle.
// You can define custom methods on it to extend its functionality as you wish.
type soccerOrderSettleDao struct {
	internalSoccerOrderSettleDao
}

var (
	// SoccerOrderSettle is globally public accessible object for table o_soccer_order_settle operations.
	SoccerOrderSettle = soccerOrderSettleDao{
		internal.NewSoccerOrderSettleDao(),
	}
)

// Fill with you ideas below.
