// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalWalletWithdrawApplicationDao is internal type for wrapping internal DAO implements.
type internalWalletWithdrawApplicationDao = *internal.WalletWithdrawApplicationDao

// walletWithdrawApplicationDao is the data access object for table u_wallet_withdraw_application.
// You can define custom methods on it to extend its functionality as you wish.
type walletWithdrawApplicationDao struct {
	internalWalletWithdrawApplicationDao
}

var (
	// WalletWithdrawApplication is globally public accessible object for table u_wallet_withdraw_application operations.
	WalletWithdrawApplication = walletWithdrawApplicationDao{
		internal.NewWalletWithdrawApplicationDao(),
	}
)

// Fill with you ideas below.
