// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"star_net/db/dao/internal"
)

// internalWithdrawAccountDao is internal type for wrapping internal DAO implements.
type internalWithdrawAccountDao = *internal.WithdrawAccountDao

// withdrawAccountDao is the data access object for table u_withdraw_account.
// You can define custom methods on it to extend its functionality as you wish.
type withdrawAccountDao struct {
	internalWithdrawAccountDao
}

var (
	// WithdrawAccount is globally public accessible object for table u_withdraw_account operations.
	WithdrawAccount = withdrawAccountDao{
		internal.NewWithdrawAccountDao(),
	}
)

// Fill with you ideas below.
