app: "api-soccer"
server:
  address: ":4102"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  jwtExpireDuration: "7D" # 7 days
  rootFilePath: "/resource/public/upload/"  # 文件上传路径
  clientMaxBodySize: "200MB"
gfToken:
  name: "star_net_user"
  cacheMode: 2 # 1 gcache  2 redis 3 file
  cacheKey: "start_net_user_token:"
  encryptKey: "koi29a83idakguqjq29asd9asd8a7jhq"
  authFailMsg: "Login timed out, please log in again"
  multiLogin: true
  globalMiddleware: true
logger:
  level: "debug"
  stdout: true
database:
  logger:
    level: "debug"
    stdout: true
  default:
    link: "mysql:root:LE2RrzrMxx6Z4sbc@tcp(127.0.0.1:3306)/soccer?loc=Local&parseTime=true"
    debug: true

redis:
  default:
    address: "127.0.0.1:63790"
    db: 1
    pass: "PqcG15w6#AX$ey0a+BYcCFIpUxLYoukAqhfnfGbnkMtYE"
pusher:
  appId: "1644349"
  key: "3400fc3f83796ca48785"
  secret: "2e84608a0d38f20e852e"
  cluster: "ap1"
elastic:
  url: "http://8.219.177.71:9200"